crud.boton.nuevo=Nuevo
crud.boton.crear=Crear
crud.boton.actualizar=Actualizar
crud.boton.eliminar=Eliminar
crud.boton.cancelar=Cancelar
crud.msg.creado=Registro creado con exito
crud.msg.actualizado=Registro actualizado con exito
crud.msg.eliminado=Registro eliminado con exito
crud.msg.nombreVacio=El nombre no puede estar vacio
menu.catalogos=Cat\u00e1logos
menu.tipoDocumento=Tipo de Documento
menu.tipoMedioContacto=Tipo de Medio de Contacto
menu.tipoExamen=Tipo de Examen
menu.examenTipoExamen=Examen - Tipo de Examen
menu.clinica.grupo=Cl\u00ednica
menu.clinica=Cl\u00ednica
menu.persona=Persona
menu.rol=Rol
menu.examenes=Ex\u00e1menes
menu.examen=Examen
menu.ordenExamen=Orden de Examen
menu.resultadoExamen=Resultado de Examen
menu.procedimientos=Procedimientos
menu.procedimiento=Procedimiento
menu.consulta=Consulta
menu.pie=\u00a9 2026 GalenoSV
sesion.sinSesion=Sin sesi\u00f3n
sesion.cerrar=Cerrar sesi\u00f3n